# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# compile CXX with /usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -I"/home/rahul/Documents/Computer Graphics/Assignment02/code(1)/code/src" -I"/home/rahul/Documents/Computer Graphics/Assignment02/code(1)/code/depends/imgui"

CXX_FLAGS = -g

